# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Artist Theme
kicker: "Thinker // Designer // YouTuber"
email: mikedoyle007@gmail.com
description: > # Using the Devtips Starter Kit as a starting point, and following along
  with the Devtips youtube channel to create a version of the Artist Theme Website.
avatar: face.jpg
bg-img: hero-bg.jpg
logo: logo.svg
blurb: <p><strong>Travis specializes in making things</strong> for human people. Most of the things he makes are <a href="http://travisneilson.com">digital interfaces</a>, but he also puts effort into crafting <a href="http://soundcloud.com/travis-neilson">next-level beats</a> and <a href="http://youtube.com/user/devtipsfordesigners">YouTube videos</a> about making codes happen.</p>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

#-----------------------------------
# Work Section

projects:
  - {name: Typo International Design Talks, folder: 'proj-1'}
  - {name: City-IN website concept, folder: 'proj-2'}
  - {name: Crispy Icons, folder: 'proj-3'}
  - {name: Flat Mobile UI/UX Concept, folder: 'proj-4'}
  - {name: Fresh It Up, folder: 'proj-5'}
  - {name: Timeline Page, folder: 'proj-6'}
  - {name: Weather Dashboard, folder: 'proj-7'}
  - {name: Stripes & Co, folder: 'proj-8'}


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
